twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        uploads_url: '%uploads_dir_name%'

when@test:
    twig:
        strict_variables: true
